export const TOKENS = {
  USER_REPO: 'USER_REPO',
  TRAINING_CONTEXT_REPO: 'TRAINING_CONTEXT_REPO',
  USER_SERVICE: 'USER_SERVICE',
  PROFILE_PARSER: 'PROFILE_PARSER',
  PROMPT_SERVICE: 'PROMPT_SERVICE',
  REGISTRATION_SERVICE: 'REGISTRATION_SERVICE',
  AI_CONTEXT: 'AI_CONTEXT',
  LLM: 'LLM',
} as const;

export type Token = (typeof TOKENS)[keyof typeof TOKENS];


