import type { MuscleGroup } from '@domain/training/types';

import { sql } from 'drizzle-orm';

import { db } from '@infra/db/drizzle';
import { exerciseMuscleGroups, exercises } from '@infra/db/schema';

import { createLogger } from '@shared/logger';

const log = createLogger('seed');

interface ExerciseSeed {
  id: string;
  name: string;
  category: 'compound' | 'isolation' | 'cardio' | 'functional' | 'mobility';
  equipment: 'barbell' | 'dumbbell' | 'bodyweight' | 'machine' | 'cable' | 'none';
  exerciseType: 'strength' | 'cardio_distance' | 'cardio_duration' | 'functional_reps' | 'isometric' | 'interval';
  description: string;
  energyCost: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  complexity: 'beginner' | 'intermediate' | 'advanced';
  typicalDurationMinutes: number;
  requiresSpotter: boolean;
  muscleGroups: Array<{
    muscle: MuscleGroup;
    involvement: 'primary' | 'secondary';
  }>;
}

const exerciseSeeds: ExerciseSeed[] = [
  // --- COMPOUND STRENGTH EXERCISES ---
  {
    id: 'c7b0899c-a0f9-47ca-a69d-4bcd531b0c95',
    name: 'Barbell Bench Press',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Classic chest compound movement with barbell',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 12,
    requiresSpotter: true,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    id: '3818f94a-0543-4241-83b4-6840d06a4e6a',
    name: 'Barbell Back Squat',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'King of leg exercises, full lower body compound',
    energyCost: 'very_high',
    complexity: 'advanced',
    typicalDurationMinutes: 15,
    requiresSpotter: true,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
      { muscle: 'lower_back', involvement: 'secondary' },
    ],
  },
  {
    id: '8254e97e-ed01-40c8-8a45-0318fe4bd4b5',
    name: 'Conventional Deadlift',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Full posterior chain compound movement',
    energyCost: 'very_high',
    complexity: 'advanced',
    typicalDurationMinutes: 12,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'primary' },
      { muscle: 'lower_back', involvement: 'primary' },
      { muscle: 'back_lats', involvement: 'secondary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'quads', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    id: '1deb3f5d-ba04-4861-896c-fa7a3a1076d6',
    name: 'Barbell Overhead Press',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Standing shoulder press, full upper body stability',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_front', involvement: 'primary' },
      { muscle: 'shoulders_side', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
      { muscle: 'chest', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    id: '913cf87b-7223-4b8b-b9f3-4222d3f37346',
    name: 'Barbell Row',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Bent-over row for back thickness',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'primary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
      { muscle: 'lower_back', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    id: '8c88ebce-f5df-4d33-afdb-0b096a0dd7a8',
    name: 'Pull-ups',
    category: 'compound',
    equipment: 'bodyweight',
    exerciseType: 'strength',
    description: 'Bodyweight back compound, vertical pull',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    id: 'b35875a4-6af8-4f95-af8a-7290ed5b7f27',
    name: 'Dips',
    category: 'compound',
    equipment: 'bodyweight',
    exerciseType: 'strength',
    description: 'Bodyweight chest and triceps compound',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'triceps', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
    ],
  },
  {
    id: '298ad0af-5a8a-4b30-99e6-34ed57450b2d',
    name: 'Barbell Hip Thrust',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Hip thrust with barbell and back on bench — primary glute builder with maximal hip extension load',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    id: 'd9401ef5-d348-4b26-9d6b-c6e9c26b7dcd',
    name: 'Romanian Deadlift',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Barbell RDL — hip hinge pattern for hamstrings and glutes, spine stays neutral',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'hamstrings', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'lower_back', involvement: 'secondary' },
      { muscle: 'back_lats', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },

  // --- ISOLATION STRENGTH EXERCISES ---
  {
    id: '49a72042-2807-4d32-b2e6-eab284987f55',
    name: 'Dumbbell Bicep Curl',
    category: 'isolation',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Classic bicep isolation',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'biceps', involvement: 'primary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
  {
    id: '646df5e1-0d1a-435a-8d58-9bdd74cecbd4',
    name: 'Tricep Pushdown',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Cable tricep isolation',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [{ muscle: 'triceps', involvement: 'primary' }],
  },
  {
    id: 'd8794819-ffc6-4d08-8336-d9bedc4e554a',
    name: 'Leg Extension',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Quad isolation machine',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [{ muscle: 'quads', involvement: 'primary' }],
  },
  {
    id: 'f1313aac-b726-4714-9901-8847df831e3e',
    name: 'Leg Curl',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Hamstring isolation machine',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [{ muscle: 'hamstrings', involvement: 'primary' }],
  },
  {
    id: 'ae3ff97c-d4ae-478a-84e9-f8805d2d9ff5',
    name: 'Lateral Raise',
    category: 'isolation',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Side delt isolation',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_side', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
    ],
  },
  {
    id: '9b39b2e2-6a32-4756-acbd-223d6c7e564b',
    name: 'Cable Fly',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Chest isolation with cables',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
    ],
  },

  // --- COMPOUND DUMBBELL EXERCISES ---
  {
    id: '464ece02-5473-43d8-b267-2712c2e43d03',
    name: 'Dumbbell Row',
    category: 'compound',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Single-arm dumbbell row with bench support — unilateral back thickness and anti-rotation',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    id: 'f80b36e2-3191-46b2-bf23-7d1c0609611d',
    name: 'Bulgarian Split Squat',
    category: 'compound',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Rear-foot-elevated split squat with dumbbells — unilateral quad and glute builder',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
      { muscle: 'calves', involvement: 'secondary' },
    ],
  },
  {
    id: '565141bf-2723-4888-8ccb-9c386c1562b3',
    name: 'Dumbbell Lunges',
    category: 'compound',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Walking or stationary lunges with dumbbells — unilateral lower body compound',
    energyCost: 'high',
    complexity: 'beginner',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'calves', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },

  // --- MACHINE / CABLE BACK EXERCISES ---
  {
    id: '72a9dca7-495c-4c64-b47d-369e98612a33',
    name: 'Chest-Supported Row, Narrow Grip',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Incline bench machine row with close parallel grip — isolates back, minimal lower back strain',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
    ],
  },
  {
    id: 'ab42e1ff-6f32-4557-af53-0d0c46d1c74e',
    name: 'Chest-Supported Row, Wide Grip',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Incline bench machine row with wide overhand grip — emphasises upper back and traps',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_traps', involvement: 'primary' },
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
    ],
  },
  {
    id: '67876573-0d23-4eff-8267-771a20ecb7f4',
    name: 'Cable Seated Row, Close Grip',
    category: 'compound',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Seated horizontal cable row with V-bar (palms facing each other) — back thickness',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
      { muscle: 'lower_back', involvement: 'secondary' },
    ],
  },
  {
    id: 'a1f0725e-6d88-4bff-950c-59de4602b9e0',
    name: 'Cable Seated Row, Wide Grip',
    category: 'compound',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Seated horizontal cable row with straight bar wide overhand grip — upper back emphasis',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_traps', involvement: 'primary' },
      { muscle: 'back_lats', involvement: 'secondary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'lower_back', involvement: 'secondary' },
    ],
  },
  {
    id: 'a0b565c8-0648-44a4-8b01-b0cb5045e795',
    name: 'Lat Pulldown',
    category: 'compound',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Cable overhead pulldown to chest — vertical pull for lat width',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
  {
    id: '74c8100f-6a9f-4d74-be1a-86068a612bd9',
    name: 'Cable Pullover',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Standing cable pullover from high pulley — targets lats and serratus',
    energyCost: 'low',
    complexity: 'intermediate',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'chest', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    id: 'ec7494e3-1d22-4b6f-9570-972c6d769a13',
    name: 'Assisted Pull-ups (Gravitron)',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Machine-assisted pull-ups for beginners building to full bodyweight pull-ups',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },

  // --- MACHINE / DUMBBELL SHOULDER EXERCISES ---
  {
    id: 'f63e6a3e-dbed-4106-9498-ee6493cb61c0',
    name: 'Machine Shoulder Press',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Seated shoulder press machine with back pad vertical — controlled overhead press',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_front', involvement: 'primary' },
      { muscle: 'shoulders_side', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    id: 'd0639e5f-1a0a-480d-a266-4289e263d5cd',
    name: 'Lateral Raise Machine',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Machine lateral raise for side deltoid — constant tension through full range',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_side', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
    ],
  },
  {
    id: 'cd12e75e-2219-4c77-bad5-3fc9450c0285',
    name: 'Reverse Pec Deck Fly',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Pec deck machine in reverse position — rear deltoid and upper back isolation',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_rear', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
    ],
  },
  {
    id: 'b6301c27-322b-44f4-a38b-a357c9ae3e12',
    name: 'Face Pull',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Cable face pull with rope — rear deltoid, rotator cuff and scapular health exercise',
    energyCost: 'low',
    complexity: 'intermediate',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_rear', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
    ],
  },
  {
    id: '146130a9-5b87-4a20-937f-3c8682003054',
    name: 'Dumbbell Shrugs',
    category: 'isolation',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Dumbbell shrugs for trapezius — standing with dumbbells at sides',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_traps', involvement: 'primary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
  {
    id: '8e6513e5-8d57-4d73-bec9-1fb40993b43e',
    name: 'Smith Machine Shrugs',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Barbell shrugs in Smith machine for trapezius — heavier loads with guided bar path',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_traps', involvement: 'primary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },

  // --- MACHINE / DUMBBELL CHEST EXERCISES ---
  {
    id: 'c0081717-7131-41ce-ad58-94dd67aa4bbd',
    name: 'Pec Deck Fly',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Pec deck butterfly machine — chest isolation with constant tension',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
    ],
  },
  {
    id: '95521942-a892-4d78-b368-5307e9fc6c3a',
    name: 'Machine Chest Press',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Horizontal chest press machine — guided movement for chest, front delts and triceps',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    id: 'e333f061-4962-4f22-93f7-fc8fec948669',
    name: 'Incline Machine Chest Press',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Incline chest press machine — upper chest emphasis with guided bar path',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'primary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    id: 'ac7b2fd7-6753-4fb3-ac44-28a7baa7b949',
    name: 'Dumbbell Bench Press',
    category: 'compound',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Flat dumbbell press — greater range of motion than barbell, independent arm movement',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    id: '3189b8e3-f655-49be-9a5c-b45e32e3e0f5',
    name: 'Incline Dumbbell Press',
    category: 'compound',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Incline dumbbell press at 30-45° — upper chest and front delt emphasis',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'primary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },

  // --- CABLE / MACHINE TRICEP EXERCISES ---
  {
    id: '8e55966f-a8c3-4252-80d2-e5a6feb85b96',
    name: 'Cable Tricep Pushdown, Straight Bar',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Overhead cable tricep pushdown with straight bar — all three heads emphasis',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [{ muscle: 'triceps', involvement: 'primary' }],
  },
  {
    id: 'cd9855ab-84c7-4948-bb07-de99d6cf3ae4',
    name: 'Cable Overhead Tricep Extension',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'High pulley cable extension behind the head with rope — long head tricep emphasis',
    energyCost: 'low',
    complexity: 'intermediate',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [{ muscle: 'triceps', involvement: 'primary' }],
  },

  // --- MACHINE / CABLE BICEP EXERCISES ---
  {
    id: '5779e648-6c8f-45ef-aec7-e69019a74252',
    name: 'Hammer Strength Bicep Curl',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Hammer Strength plate-loaded curl machine — isolated bilateral or unilateral bicep curl',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'biceps', involvement: 'primary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
  {
    id: '6289bc3f-da6e-4d9f-87f8-28c83b63c6ea',
    name: 'Cable Hammer Curl',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Low pulley cable curl with rope attachment, neutral grip — brachialis and bicep',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'biceps', involvement: 'primary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },

  // --- LEG MACHINE EXERCISES ---
  {
    id: 'cc37dd85-2c51-4ebc-9a18-8c7b83e6aa11',
    name: 'Vertical Leg Press',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Leg press with vertical sled at 90° — maximum quad and glute loading',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'calves', involvement: 'secondary' },
    ],
  },
  {
    id: '0bdcece7-7811-4f14-a0f0-cc41e61b13c8',
    name: 'Horizontal Leg Press',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Seated horizontal leg press machine — quad, glute and hamstring compound movement',
    energyCost: 'high',
    complexity: 'beginner',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'calves', involvement: 'secondary' },
    ],
  },
  {
    id: '54c33ada-e13c-470a-b55f-200965acfdd8',
    name: 'Calf Press on Leg Press Machine',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Calf raises performed on the leg press machine platform — gastrocnemius isolation',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [{ muscle: 'calves', involvement: 'primary' }],
  },
  {
    id: 'f6ae6288-f8eb-479c-bc29-6ccb7473eff3',
    name: 'Hack Squat Machine',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Machine hack squat — quad-dominant compound with back support and guided sled path',
    energyCost: 'high',
    complexity: 'beginner',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'secondary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'calves', involvement: 'secondary' },
    ],
  },
  {
    id: '3d19e0fd-7dad-458e-9d24-036898964666',
    name: 'Standing Calf Raise Machine',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Standing calf raise machine — gastrocnemius isolation with full stretch and contraction',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [{ muscle: 'calves', involvement: 'primary' }],
  },
  {
    id: '696c97ab-bdfc-4bb3-bc7d-5d3bae8b9289',
    name: 'Seated Calf Raise Machine',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Seated calf raise machine — soleus isolation with bent-knee position',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [{ muscle: 'calves', involvement: 'primary' }],
  },

  // --- CORE / POSTERIOR CHAIN / FUNCTIONAL ---
  {
    id: '3cf83260-4148-4ef2-8de0-534c3bbb263f',
    name: 'Hyperextension',
    category: 'compound',
    equipment: 'bodyweight',
    exerciseType: 'strength',
    description: 'Roman chair back extension — lower back, glute and hamstring posterior chain exercise',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'lower_back', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'secondary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
    ],
  },
  {
    id: 'a7e5618a-e621-4c42-916b-1d4053a9cbb8',
    name: 'Hanging Leg Raise',
    category: 'functional',
    equipment: 'bodyweight',
    exerciseType: 'functional_reps',
    description: 'Hanging from bar, raise legs to horizontal or above — lower abs and hip flexor strength',
    energyCost: 'medium',
    complexity: 'intermediate',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'abs', involvement: 'primary' },
      { muscle: 'core', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
  {
    id: '87755f64-2dab-43c6-a2a1-54852046e886',
    name: 'Cable Crunch',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Kneeling cable crunch with rope — weighted abdominal exercise with progressive overload',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'abs', involvement: 'primary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    id: '7e788a8a-90ed-4dab-af6c-cadcc5c968c5',
    name: 'Ab Coaster',
    category: 'functional',
    equipment: 'machine',
    exerciseType: 'functional_reps',
    description: 'Ab Coaster machine — kneeling crunch arc movement for lower and full abs',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'abs', involvement: 'primary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },

  // --- CARDIO EXERCISES ---
  {
    id: 'a8658a5d-d2eb-4aeb-a179-92ed8cc2c27e',
    name: 'Treadmill',
    category: 'cardio',
    equipment: 'machine',
    exerciseType: 'cardio_distance',
    description: 'Treadmill running or walking — adjustable speed and incline',
    energyCost: 'high',
    complexity: 'beginner',
    typicalDurationMinutes: 30,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'lower_body_endurance', involvement: 'primary' },
    ],
  },
  {
    id: '8262cce4-023f-415e-81de-871678f96488',
    name: 'Elliptical Trainer',
    category: 'cardio',
    equipment: 'machine',
    exerciseType: 'cardio_duration',
    description: 'Elliptical cross-trainer — low-impact full body cardio',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 30,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'lower_body_endurance', involvement: 'primary' },
      { muscle: 'quads', involvement: 'secondary' },
      { muscle: 'glutes', involvement: 'secondary' },
    ],
  },
  {
    id: 'da89020e-f54a-4573-b70b-764833ae761a',
    name: 'Running',
    category: 'cardio',
    equipment: 'none',
    exerciseType: 'cardio_distance',
    description: 'Outdoor running',
    energyCost: 'high',
    complexity: 'beginner',
    typicalDurationMinutes: 30,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'lower_body_endurance', involvement: 'primary' },
    ],
  },
  {
    id: 'f36dc067-0f4f-4fc0-8075-0d4fc873ba01',
    name: 'Cycling',
    category: 'cardio',
    equipment: 'machine',
    exerciseType: 'cardio_distance',
    description: 'Stationary or outdoor cycling',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 30,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'lower_body_endurance', involvement: 'primary' },
      { muscle: 'quads', involvement: 'secondary' },
    ],
  },
  {
    id: 'bf6a2f9e-efe9-4b39-b4d1-0dd5126f5c5f',
    name: 'Rowing Machine',
    category: 'cardio',
    equipment: 'machine',
    exerciseType: 'cardio_duration',
    description: 'Full body cardio on rowing machine',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 20,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'full_body', involvement: 'primary' },
      { muscle: 'back_lats', involvement: 'secondary' },
      { muscle: 'quads', involvement: 'secondary' },
    ],
  },

  // --- FUNCTIONAL EXERCISES ---
  {
    id: '37df486c-cf2f-4320-bbb6-9f7482d0c6af',
    name: 'Burpees',
    category: 'functional',
    equipment: 'bodyweight',
    exerciseType: 'functional_reps',
    description: 'Full body explosive functional movement',
    energyCost: 'very_high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'full_body', involvement: 'primary' },
      { muscle: 'cardio_system', involvement: 'primary' },
    ],
  },
  {
    id: 'bf68fdc0-6596-47bd-9cb8-6ff58ae7998c',
    name: 'Box Jumps',
    category: 'functional',
    equipment: 'bodyweight',
    exerciseType: 'functional_reps',
    description: 'Explosive lower body power',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'calves', involvement: 'secondary' },
    ],
  },
  {
    id: '08b9f0f0-7a02-46cc-b0aa-559f653d94c1',
    name: 'Plank',
    category: 'functional',
    equipment: 'bodyweight',
    exerciseType: 'isometric',
    description: 'Core stability hold',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 5,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'core_stability', involvement: 'primary' },
      { muscle: 'abs', involvement: 'primary' },
      { muscle: 'lower_back', involvement: 'secondary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
      { muscle: 'glutes', involvement: 'secondary' },
    ],
  },
  {
    id: '4a46d68a-c009-4d98-bb73-af4edc7df116',
    name: 'Jump Rope',
    category: 'functional',
    equipment: 'none',
    exerciseType: 'interval',
    description: 'Cardio and coordination interval training',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 15,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'calves', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
  {
    id: '869708aa-31f1-4920-af1c-63f0056de3bf',
    name: 'Dumbbell Hammer Curl',
    category: 'isolation',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Neutral grip dumbbell curl targeting brachialis and brachioradialis',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'biceps', involvement: 'primary' },
      { muscle: 'forearms', involvement: 'primary' },
    ],
  },
];

export async function seedExercises() {
  log.info({ count: exerciseSeeds.length }, 'seeding exercises');

  for (const seed of exerciseSeeds) {
    // Insert with fixed UUID — ON CONFLICT (id) DO UPDATE keeps name canonical
    const [upserted] = await db
      .insert(exercises)
      .values({
        id: seed.id,
        name: seed.name,
        category: seed.category,
        equipment: seed.equipment,
        exerciseType: seed.exerciseType,
        description: seed.description,
        energyCost: seed.energyCost,
        complexity: seed.complexity,
        typicalDurationMinutes: seed.typicalDurationMinutes,
        requiresSpotter: seed.requiresSpotter,
      })
      .onConflictDoUpdate({
        target: exercises.id,
        set: { name: sql`EXCLUDED.name` },
      })
      .returning();

    const exerciseId = upserted.id;

    // Always upsert muscle group mappings (idempotent)
    for (const mg of seed.muscleGroups) {
      await db
        .insert(exerciseMuscleGroups)
        .values({
          exerciseId,
          muscleGroup: mg.muscle,
          involvement: mg.involvement,
        })
        .onConflictDoNothing();
    }

    log.debug({ id: exerciseId, name: seed.name, category: seed.category }, 'exercise seeded');
  }

  log.info({ count: exerciseSeeds.length }, 'exercises seeded successfully');
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  await seedExercises();
  process.exit(0);
}
