import type { MuscleGroup } from '@domain/training/types';

import { db } from '@infra/db/drizzle';
import { exerciseMuscleGroups, exercises } from '@infra/db/schema';

import { createLogger } from '@shared/logger';

const log = createLogger('seed');

interface ExerciseSeed {
  name: string;
  category: 'compound' | 'isolation' | 'cardio' | 'functional' | 'mobility';
  equipment: 'barbell' | 'dumbbell' | 'bodyweight' | 'machine' | 'cable' | 'none';
  exerciseType: 'strength' | 'cardio_distance' | 'cardio_duration' | 'functional_reps' | 'isometric' | 'interval';
  description: string;
  energyCost: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  complexity: 'beginner' | 'intermediate' | 'advanced';
  typicalDurationMinutes: number;
  requiresSpotter: boolean;
  muscleGroups: Array<{
    muscle: MuscleGroup;
    involvement: 'primary' | 'secondary';
  }>;
}

const exerciseSeeds: ExerciseSeed[] = [
  // --- COMPOUND STRENGTH EXERCISES ---
  {
    name: 'Barbell Bench Press',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Classic chest compound movement with barbell',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 12,
    requiresSpotter: true,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    name: 'Barbell Back Squat',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'King of leg exercises, full lower body compound',
    energyCost: 'very_high',
    complexity: 'advanced',
    typicalDurationMinutes: 15,
    requiresSpotter: true,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
      { muscle: 'lower_back', involvement: 'secondary' },
    ],
  },
  {
    name: 'Conventional Deadlift',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Full posterior chain compound movement',
    energyCost: 'very_high',
    complexity: 'advanced',
    typicalDurationMinutes: 12,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'primary' },
      { muscle: 'lower_back', involvement: 'primary' },
      { muscle: 'back_lats', involvement: 'secondary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'quads', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    name: 'Barbell Overhead Press',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Standing shoulder press, full upper body stability',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_front', involvement: 'primary' },
      { muscle: 'shoulders_side', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
      { muscle: 'chest', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    name: 'Barbell Row',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Bent-over row for back thickness',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'primary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
      { muscle: 'lower_back', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    name: 'Pull-ups',
    category: 'compound',
    equipment: 'bodyweight',
    exerciseType: 'strength',
    description: 'Bodyweight back compound, vertical pull',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    name: 'Dips',
    category: 'compound',
    equipment: 'bodyweight',
    exerciseType: 'strength',
    description: 'Bodyweight chest and triceps compound',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'triceps', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
    ],
  },
  {
    name: 'Barbell Hip Thrust',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Hip thrust with barbell and back on bench — primary glute builder with maximal hip extension load',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    name: 'Romanian Deadlift',
    category: 'compound',
    equipment: 'barbell',
    exerciseType: 'strength',
    description: 'Barbell RDL — hip hinge pattern for hamstrings and glutes, spine stays neutral',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'hamstrings', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'lower_back', involvement: 'secondary' },
      { muscle: 'back_lats', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },

  // --- ISOLATION STRENGTH EXERCISES ---
  {
    name: 'Dumbbell Bicep Curl',
    category: 'isolation',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Classic bicep isolation',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'biceps', involvement: 'primary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
  {
    name: 'Tricep Pushdown',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Cable tricep isolation',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'triceps', involvement: 'primary' },
    ],
  },
  {
    name: 'Leg Extension',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Quad isolation machine',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
    ],
  },
  {
    name: 'Leg Curl',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Hamstring isolation machine',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'hamstrings', involvement: 'primary' },
    ],
  },
  {
    name: 'Lateral Raise',
    category: 'isolation',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Side delt isolation',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_side', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
    ],
  },
  {
    name: 'Cable Fly',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Chest isolation with cables',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
    ],
  },

  // --- COMPOUND DUMBBELL EXERCISES ---
  {
    name: 'Dumbbell Row',
    category: 'compound',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Single-arm dumbbell row with bench support — unilateral back thickness and anti-rotation',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    name: 'Bulgarian Split Squat',
    category: 'compound',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Rear-foot-elevated split squat with dumbbells — unilateral quad and glute builder',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
      { muscle: 'calves', involvement: 'secondary' },
    ],
  },
  {
    name: 'Dumbbell Lunges',
    category: 'compound',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Walking or stationary lunges with dumbbells — unilateral lower body compound',
    energyCost: 'high',
    complexity: 'beginner',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'calves', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },

  // --- MACHINE / CABLE BACK EXERCISES ---
  {
    name: 'Chest-Supported Row, Narrow Grip',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Incline bench machine row with close parallel grip — isolates back, minimal lower back strain',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
    ],
  },
  {
    name: 'Chest-Supported Row, Wide Grip',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Incline bench machine row with wide overhand grip — emphasises upper back and traps',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_traps', involvement: 'primary' },
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
    ],
  },
  {
    name: 'Cable Seated Row, Close Grip',
    category: 'compound',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Seated horizontal cable row with V-bar (palms facing each other) — back thickness',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
      { muscle: 'lower_back', involvement: 'secondary' },
    ],
  },
  {
    name: 'Cable Seated Row, Wide Grip',
    category: 'compound',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Seated horizontal cable row with straight bar wide overhand grip — upper back emphasis',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_traps', involvement: 'primary' },
      { muscle: 'back_lats', involvement: 'secondary' },
      { muscle: 'shoulders_rear', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'lower_back', involvement: 'secondary' },
    ],
  },
  {
    name: 'Lat Pulldown',
    category: 'compound',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Cable overhead pulldown to chest — vertical pull for lat width',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
  {
    name: 'Cable Pullover',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Standing cable pullover from high pulley — targets lats and serratus',
    energyCost: 'low',
    complexity: 'intermediate',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'chest', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    name: 'Assisted Pull-ups (Gravitron)',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Machine-assisted pull-ups for beginners building to full bodyweight pull-ups',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_lats', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
      { muscle: 'biceps', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },

  // --- MACHINE / DUMBBELL SHOULDER EXERCISES ---
  {
    name: 'Machine Shoulder Press',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Seated shoulder press machine with back pad vertical — controlled overhead press',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_front', involvement: 'primary' },
      { muscle: 'shoulders_side', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    name: 'Lateral Raise Machine',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Machine lateral raise for side deltoid — constant tension through full range',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_side', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
    ],
  },
  {
    name: 'Reverse Pec Deck Fly',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Pec deck machine in reverse position — rear deltoid and upper back isolation',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_rear', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
    ],
  },
  {
    name: 'Face Pull',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Cable face pull with rope — rear deltoid, rotator cuff and scapular health exercise',
    energyCost: 'low',
    complexity: 'intermediate',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'shoulders_rear', involvement: 'primary' },
      { muscle: 'back_traps', involvement: 'secondary' },
    ],
  },
  {
    name: 'Dumbbell Shrugs',
    category: 'isolation',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Dumbbell shrugs for trapezius — standing with dumbbells at sides',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_traps', involvement: 'primary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
  {
    name: 'Smith Machine Shrugs',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Barbell shrugs in Smith machine for trapezius — heavier loads with guided bar path',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'back_traps', involvement: 'primary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },

  // --- MACHINE / DUMBBELL CHEST EXERCISES ---
  {
    name: 'Pec Deck Fly',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Pec deck butterfly machine — chest isolation with constant tension',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
    ],
  },
  {
    name: 'Machine Chest Press',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Horizontal chest press machine — guided movement for chest, front delts and triceps',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    name: 'Incline Machine Chest Press',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Incline chest press machine — upper chest emphasis with guided bar path',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'primary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    name: 'Dumbbell Bench Press',
    category: 'compound',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Flat dumbbell press — greater range of motion than barbell, independent arm movement',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },
  {
    name: 'Incline Dumbbell Press',
    category: 'compound',
    equipment: 'dumbbell',
    exerciseType: 'strength',
    description: 'Incline dumbbell press at 30-45° — upper chest and front delt emphasis',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'chest', involvement: 'primary' },
      { muscle: 'shoulders_front', involvement: 'primary' },
      { muscle: 'triceps', involvement: 'secondary' },
    ],
  },

  // --- CABLE / MACHINE TRICEP EXERCISES ---
  {
    name: 'Cable Tricep Pushdown, Straight Bar',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Overhead cable tricep pushdown with straight bar — all three heads emphasis',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'triceps', involvement: 'primary' },
    ],
  },
  {
    name: 'Cable Overhead Tricep Extension',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'High pulley cable extension behind the head with rope — long head tricep emphasis',
    energyCost: 'low',
    complexity: 'intermediate',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'triceps', involvement: 'primary' },
    ],
  },

  // --- MACHINE / CABLE BICEP EXERCISES ---
  {
    name: 'Hammer Strength Bicep Curl',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Hammer Strength plate-loaded curl machine — isolated bilateral or unilateral bicep curl',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'biceps', involvement: 'primary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
  {
    name: 'Cable Hammer Curl',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Low pulley cable curl with rope attachment, neutral grip — brachialis and bicep',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'biceps', involvement: 'primary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },

  // --- LEG MACHINE EXERCISES ---
  {
    name: 'Vertical Leg Press',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Leg press with vertical sled at 90° — maximum quad and glute loading',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'calves', involvement: 'secondary' },
    ],
  },
  {
    name: 'Horizontal Leg Press',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Seated horizontal leg press machine — quad, glute and hamstring compound movement',
    energyCost: 'high',
    complexity: 'beginner',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'calves', involvement: 'secondary' },
    ],
  },
  {
    name: 'Calf Press on Leg Press Machine',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Calf raises performed on the leg press machine platform — gastrocnemius isolation',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'calves', involvement: 'primary' },
    ],
  },
  {
    name: 'Hack Squat Machine',
    category: 'compound',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Machine hack squat — quad-dominant compound with back support and guided sled path',
    energyCost: 'high',
    complexity: 'beginner',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'secondary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
      { muscle: 'calves', involvement: 'secondary' },
    ],
  },
  {
    name: 'Standing Calf Raise Machine',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Standing calf raise machine — gastrocnemius isolation with full stretch and contraction',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'calves', involvement: 'primary' },
    ],
  },
  {
    name: 'Seated Calf Raise Machine',
    category: 'isolation',
    equipment: 'machine',
    exerciseType: 'strength',
    description: 'Seated calf raise machine — soleus isolation with bent-knee position',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'calves', involvement: 'primary' },
    ],
  },

  // --- CORE / POSTERIOR CHAIN / FUNCTIONAL ---
  {
    name: 'Hyperextension',
    category: 'compound',
    equipment: 'bodyweight',
    exerciseType: 'strength',
    description: 'Roman chair back extension — lower back, glute and hamstring posterior chain exercise',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'lower_back', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'secondary' },
      { muscle: 'hamstrings', involvement: 'secondary' },
    ],
  },
  {
    name: 'Hanging Leg Raise',
    category: 'functional',
    equipment: 'bodyweight',
    exerciseType: 'functional_reps',
    description: 'Hanging from bar, raise legs to horizontal or above — lower abs and hip flexor strength',
    energyCost: 'medium',
    complexity: 'intermediate',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'abs', involvement: 'primary' },
      { muscle: 'core', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
  {
    name: 'Cable Crunch',
    category: 'isolation',
    equipment: 'cable',
    exerciseType: 'strength',
    description: 'Kneeling cable crunch with rope — weighted abdominal exercise with progressive overload',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'abs', involvement: 'primary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },
  {
    name: 'Ab Coaster',
    category: 'functional',
    equipment: 'machine',
    exerciseType: 'functional_reps',
    description: 'Ab Coaster machine — kneeling crunch arc movement for lower and full abs',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 6,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'abs', involvement: 'primary' },
      { muscle: 'core', involvement: 'secondary' },
    ],
  },

  // --- CARDIO EXERCISES ---
  {
    name: 'Treadmill',
    category: 'cardio',
    equipment: 'machine',
    exerciseType: 'cardio_distance',
    description: 'Treadmill running or walking — adjustable speed and incline',
    energyCost: 'high',
    complexity: 'beginner',
    typicalDurationMinutes: 30,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'lower_body_endurance', involvement: 'primary' },
    ],
  },
  {
    name: 'Elliptical Trainer',
    category: 'cardio',
    equipment: 'machine',
    exerciseType: 'cardio_duration',
    description: 'Elliptical cross-trainer — low-impact full body cardio',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 30,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'lower_body_endurance', involvement: 'primary' },
      { muscle: 'quads', involvement: 'secondary' },
      { muscle: 'glutes', involvement: 'secondary' },
    ],
  },
  {
    name: 'Running',
    category: 'cardio',
    equipment: 'none',
    exerciseType: 'cardio_distance',
    description: 'Outdoor running',
    energyCost: 'high',
    complexity: 'beginner',
    typicalDurationMinutes: 30,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'lower_body_endurance', involvement: 'primary' },
    ],
  },
  {
    name: 'Cycling',
    category: 'cardio',
    equipment: 'machine',
    exerciseType: 'cardio_distance',
    description: 'Stationary or outdoor cycling',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 30,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'lower_body_endurance', involvement: 'primary' },
      { muscle: 'quads', involvement: 'secondary' },
    ],
  },
  {
    name: 'Rowing Machine',
    category: 'cardio',
    equipment: 'machine',
    exerciseType: 'cardio_duration',
    description: 'Full body cardio on rowing machine',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 20,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'full_body', involvement: 'primary' },
      { muscle: 'back_lats', involvement: 'secondary' },
      { muscle: 'quads', involvement: 'secondary' },
    ],
  },

  // --- FUNCTIONAL EXERCISES ---
  {
    name: 'Burpees',
    category: 'functional',
    equipment: 'bodyweight',
    exerciseType: 'functional_reps',
    description: 'Full body explosive functional movement',
    energyCost: 'very_high',
    complexity: 'intermediate',
    typicalDurationMinutes: 10,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'full_body', involvement: 'primary' },
      { muscle: 'cardio_system', involvement: 'primary' },
    ],
  },
  {
    name: 'Box Jumps',
    category: 'functional',
    equipment: 'bodyweight',
    exerciseType: 'functional_reps',
    description: 'Explosive lower body power',
    energyCost: 'high',
    complexity: 'intermediate',
    typicalDurationMinutes: 8,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'quads', involvement: 'primary' },
      { muscle: 'glutes', involvement: 'primary' },
      { muscle: 'calves', involvement: 'secondary' },
    ],
  },
  {
    name: 'Plank',
    category: 'functional',
    equipment: 'bodyweight',
    exerciseType: 'isometric',
    description: 'Core stability hold',
    energyCost: 'low',
    complexity: 'beginner',
    typicalDurationMinutes: 5,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'core_stability', involvement: 'primary' },
      { muscle: 'abs', involvement: 'primary' },
      { muscle: 'lower_back', involvement: 'secondary' },
      { muscle: 'shoulders_front', involvement: 'secondary' },
      { muscle: 'glutes', involvement: 'secondary' },
    ],
  },
  {
    name: 'Jump Rope',
    category: 'functional',
    equipment: 'none',
    exerciseType: 'interval',
    description: 'Cardio and coordination interval training',
    energyCost: 'medium',
    complexity: 'beginner',
    typicalDurationMinutes: 15,
    requiresSpotter: false,
    muscleGroups: [
      { muscle: 'cardio_system', involvement: 'primary' },
      { muscle: 'calves', involvement: 'secondary' },
      { muscle: 'forearms', involvement: 'secondary' },
    ],
  },
];

export async function seedExercises() {
  log.info({ count: exerciseSeeds.length }, 'seeding exercises');

  for (const seed of exerciseSeeds) {
    // Insert exercise
    const [exercise] = await db
      .insert(exercises)
      .values({
        name: seed.name,
        category: seed.category,
        equipment: seed.equipment,
        exerciseType: seed.exerciseType,
        description: seed.description,
        energyCost: seed.energyCost,
        complexity: seed.complexity,
        typicalDurationMinutes: seed.typicalDurationMinutes,
        requiresSpotter: seed.requiresSpotter,
      })
      .onConflictDoNothing()
      .returning();

    if (!exercise) {
      log.debug({ name: seed.name }, 'exercise already exists, skipping');
      continue;
    }

    // Insert muscle group mappings
    for (const mg of seed.muscleGroups) {
      await db.insert(exerciseMuscleGroups).values({
        exerciseId: exercise.id,
        muscleGroup: mg.muscle,
        involvement: mg.involvement,
      }).onConflictDoNothing();
    }

    log.debug({ name: seed.name, category: seed.category }, 'exercise seeded');
  }

  log.info({ count: exerciseSeeds.length }, 'exercises seeded successfully');
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  await seedExercises();
  process.exit(0);
}
